#pragma once
// =============================================================================
// include/ed/symmetry/irreps.h
//
// Numerical irreducible-representation decomposition for a finite group given
// as a set of site permutations (the `max_clique` of a SymmetryGroupInfo).
//
// This is the engine for FULL (possibly non-abelian) symmetry-adapted ED. The
// abelian path only ever needs 1-D characters χ(g); a genuinely non-abelian
// point group (e.g. C4v, D4) has d≥2 irreps whose d×d matrices D^Γ(g) are
// required to build the symmetry-adapted basis and to weight the matvec.
//
// Algorithm (robust, O(|G|^3); |G| is small — at most a few hundred):
//
//   The group algebra C[G] is the LEFT regular representation L(g)·e_x = e_{gx}.
//   Its commutant is the RIGHT regular representation R(h)·e_x = e_{x h^{-1}},
//   which commutes with every L(g). Under the isotypic decomposition
//       C[G] ≅ ⊕_Γ  C^{d_Γ} ⊗ C^{d_Γ}    (L acts on the 1st factor, R on the 2nd)
//   a GENERIC Hermitian element of the commutant
//       M = Σ_h c_h R(h)   with  c_{h^{-1}} = conj(c_h)  (so M = M†)
//   acts within each isotypic block as I_{d_Γ} ⊗ B_Γ with B_Γ a generic d_Γ×d_Γ
//   Hermitian matrix. Hence:
//     * every eigenspace of M is L-invariant and is a SINGLE irreducible copy of
//       some Γ (dimension d_Γ);
//     * eigenspaces sharing the same character belong to the same Γ.
//   So we eigendecompose ONE Hermitian |G|×|G| matrix, group eigenvectors into
//   eigenspaces, read off D^Γ(g)_{mn} = ⟨v_m| L(g) |v_n⟩ per eigenspace, and
//   deduplicate by character. Σ_Γ d_Γ² == |G| and #irreps == #conjugacy-classes
//   are checked.
//
// The result is gauge-dependent only up to a unitary within each irrep (the
// physics — block spectra and d_Γ degeneracies — is gauge-invariant).
// =============================================================================

#include <complex>
#include <cstdint>
#include <string>
#include <vector>

namespace ed::symmetry {

struct IrrepData {
    int dim = 1;  ///< d_Γ
    /// χ_Γ(g) for every group element, length |G| (indexed as in max_clique).
    std::vector<std::complex<double>> character;
    /// D^Γ(g): one d×d matrix per group element, row-major
    /// (matrices[g][m*dim + n] == D^Γ(g)_{mn}), length |G|.
    std::vector<std::vector<std::complex<double>>> matrices;

    /// Convenience: the (n,n) diagonal partner element D^Γ(g)_{nn} over all g.
    [[nodiscard]] std::vector<std::complex<double>>
    partner_diagonal(int n) const;
};

struct GroupIrreps {
    int order = 1;                          ///< |G|
    int num_classes = 1;                    ///< number of conjugacy classes (== #irreps)
    std::vector<int> inverse;               ///< inverse[a] = index of perm_a^{-1}
    std::vector<std::vector<int>> mult;     ///< mult[a][b] = index of (perm_a ∘ perm_b)
    std::vector<int> class_of;              ///< class_of[a] = conjugacy class index of a
    std::vector<IrrepData> irreps;          ///< one per distinct irrep

    [[nodiscard]] bool is_abelian() const noexcept {
        for (const auto& ir : irreps) if (ir.dim > 1) return false;
        return true;
    }
};

/// Decompose the finite group generated by (and equal to) `max_clique` — a list
/// of site permutations on `n_sites` bits, closed under composition — into its
/// irreducible representations. `max_clique[0]` is assumed to be the identity
/// (as produced by `generate_group`); this is not required but conventional.
///
/// Throws std::runtime_error if `max_clique` is not closed under composition or
/// if the numerical decomposition fails the Σd_Γ² == |G| / orthogonality checks.
[[nodiscard]] GroupIrreps
decompose_irreps(const std::vector<std::vector<int>>& max_clique, int n_sites);

}  // namespace ed::symmetry
