"""``qed._solve.symmetry_input``: normalising the ``symmetry=`` argument.

Carved out of ``workflow.py`` (WP11). Turns whatever a caller passed
(``GeneratorSet`` / raw permutation list / group dict / duck-typed carrier)
into the closed group ``info`` dict the streaming kernels and the directory
writers both read, and resolves a ``sector=`` quantum-number tuple against
that dict's sector table.
"""

from __future__ import annotations

from typing import Any, Optional, Sequence, Union

from .._core import Operator  # type: ignore[attr-defined]
from ..discovery import GeneratorSet



# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

Permutation = list[int]
SymmetryArg = Union["GeneratorSet", Sequence[Permutation], dict[str, Any], None]


def _operator_conserves_sz(operator: Operator) -> bool:
    """True iff every Hamiltonian term commutes with total Sz.

    Each elementary operator changes total Sz by op_type 0 (S+) -> +1,
    1 (S-) -> -1, 2 (Sz) -> 0. A term conserves Sz iff the net change
    over its factors is zero. Used to decide whether
    :func:`full_spectrum` can decompose by magnetisation (loop n_up)
    in addition to the spatial irreps. Conservative: any parse failure
    -> ``False`` (treat as non-conserving, fall back to the full span).
    """
    # Prefer the operator's own predicate when present (authoritative).
    try:
        return bool(operator.conserves_sz())
    except Exception:
        pass
    _delta = {0: 1, 1: -1, 2: 0}
    try:
        for op_type, _site, _c in operator.iter_one_body_terms():
            if _delta.get(int(op_type), 1) != 0:
                return False
        for op1, _s1, op2, _s2, _c in operator.iter_two_body_terms():
            if _delta.get(int(op1), 1) + _delta.get(int(op2), 1) != 0:
                return False
        for op1, _s1, op2, _s2, op3, _s3, _c in operator.iter_three_body_terms():
            if (_delta.get(int(op1), 1) + _delta.get(int(op2), 1)
                    + _delta.get(int(op3), 1) != 0):
                return False
    except Exception:
        return False
    return True


def _normalize_symmetry_info(
    operator: Operator, symmetry: SymmetryArg
) -> Optional[dict[str, Any]]:
    """Normalise a symmetry argument into the group ``info`` dict the
    streaming kernel reads, or ``None`` for the trivial (no spatial
    symmetry) case."""
    from ..symmetry import group_from_generators

    if symmetry is None:
        return None
    if isinstance(symmetry, GeneratorSet):
        gens = symmetry.generators
        return (group_from_generators(int(operator.num_sites), gens)
                if gens else None)
    if isinstance(symmetry, dict):
        return symmetry
    if isinstance(symmetry, (list, tuple)):
        gens = [list(map(int, p)) for p in symmetry]
        return (group_from_generators(int(operator.num_sites), gens)
                if gens else None)
    # Duck-typed GeneratorSet-shaped carrier (a ``.generators`` attribute,
    # optionally ``.star_perms``): qed.solve accepts these, so qed.thermal
    # must too -- the two verbs took inconsistent symmetry= inputs, a trap
    # for callers who reuse one symmetry object across both.
    gens = getattr(symmetry, "generators", None)
    if gens is not None:
        gl = [list(map(int, p)) for p in gens]
        return (group_from_generators(int(operator.num_sites), gl)
                if gl else None)
    raise TypeError(
        f"symmetry must be GeneratorSet, list[Permutation], dict, or an "
        f"object exposing a .generators attribute, got "
        f"{type(symmetry).__name__}"
    )


def _raw_generators(symmetry: SymmetryArg) -> Optional[list[list[int]]]:
    """The UNRESTRICTED site-permutation generators of ``symmetry`` (before
    the abelian-subgroup guard in ``group_from_generators``). Used to decide
    whether the spatial group is non-abelian and to feed split_nonabelian
    (Stage 9c; previously the monolithic SAB engine)."""
    if symmetry is None:
        return None
    if isinstance(symmetry, GeneratorSet):
        gens = symmetry.generators
    elif isinstance(symmetry, (list, tuple)):
        gens = symmetry
    elif isinstance(symmetry, dict):
        gens = symmetry.get("generators")
    else:
        gens = getattr(symmetry, "generators", None)  # duck-typed carrier
        if gens is None:
            return None
    return [list(map(int, p)) for p in gens] if gens else None


def _generators_nonabelian(gens: list[list[int]]) -> bool:
    """True iff the group generated by ``gens`` is non-abelian. A group
    generated by pairwise-commuting elements is abelian, so checking the
    generators pairwise suffices (composition convention is immaterial for
    a commutativity test)."""
    if not gens or len(gens) < 2:
        return False
    def comp(a: list[int], b: list[int]) -> list[int]:
        return [a[b[i]] for i in range(len(b))]
    for i in range(len(gens)):
        for j in range(i + 1, len(gens)):
            if comp(gens[i], gens[j]) != comp(gens[j], gens[i]):
                return True
    return False


def _resolve_sector_quantum_numbers(info: dict[str, Any],
                                    sector: Sequence[int]) -> int:
    """QN tuple -> the RAW sector index the C++ filter selects on.

    ``sector=`` names one quantum number per generator; ``selected_sectors``
    is documented as raw sector INDICES ("only sectors whose linear index
    appears in this list"). The two axes coincide ONLY for a single generator,
    which is why every ring test passed while a 4x4 torus silently answered
    every irrep with the global ground state.

    ``info['sectors']`` is the table -- Python builds it itself and writes it
    to ``sector_metadata.json`` -- so the mapping is a lookup, not a guess:
    match on ``quantum_numbers``, return ``sector_id``.
    """
    qn_want = [int(q) for q in sector]
    sectors = list(info.get("sectors", []) or [])
    if not sectors:
        raise RuntimeError(
            "qed.solve: sector= was given but the symmetry info carries no "
            "sector table to resolve it against.")
    for s in sectors:
        if [int(x) for x in s.get("quantum_numbers", [])] == qn_want:
            return int(s.get("sector_id", 0))
    n_gen = len(sectors[0].get("quantum_numbers", []))
    if len(qn_want) != n_gen:
        raise ValueError(
            f"qed.solve: sector={qn_want} names {len(qn_want)} quantum "
            f"number(s) but this symmetry has {n_gen} generator(s); pass one "
            f"per generator.")
    raise ValueError(
        f"qed.solve: sector={qn_want} is not an irrep of this group. Valid "
        f"quantum numbers are "
        f"{sorted([int(x) for x in s.get('quantum_numbers', [])] for s in sectors)[:8]}"
        f"{' ...' if len(sectors) > 8 else ''}. (Generators need not be "
        f"independent -- when they carry a relation, most QN tuples are not "
        f"characters of the group at all.)")


def _closed_symmetry_info(info: dict[str, Any]) -> dict[str, Any]:
    """The group ``info`` dict with its element list closed.

    The streaming kernel needs ``max_clique`` (the enumerated group). A dict
    produced by ``group_from_generators`` already carries it and is returned
    unchanged; a raw dict holding only ``generators`` (e.g. from a
    third-party source) is closed here through the symmetry DSL, which also
    supplies ``generator_orders`` and the (relation-filtered, contiguously
    numbered) ``sectors`` table. The caller's generators are kept verbatim
    unless the DSL restricted them (non-abelian input -> maximal abelian
    subgroup), in which case its own generator list is the one the orders
    and quantum numbers refer to.

    Both the directory writer and the in-memory symmetric bindings take
    their group from this dict, and ``sector=`` is resolved against the same
    table. (C++ re-filters phantom irreps and renumbers the survivors; a
    closed table is already filtered and contiguous, so that is a no-op
    here. Only a caller-supplied ``max_clique`` + UNFILTERED ``sectors``
    table can still be renumbered under the ``sector=`` lookup.)
    """
    if info.get("max_clique"):
        return info
    from ..symmetry import group_from_generators  # noqa: WPS433
    generators = info.get("generators", []) or []
    info2 = group_from_generators(
        len(generators[0]) if generators else 0,
        [list(map(int, g)) for g in generators],
    )
    closed = dict(info)
    closed["max_clique"] = info2["max_clique"]
    closed["generator_orders"] = info2["generator_orders"]
    closed["sectors"] = info2["sectors"]
    if len(generators) != len(info2["generator_orders"]):
        closed["generators"] = info2.get("generators", generators)
    else:
        closed["generators"] = [list(map(int, g)) for g in generators]
    return closed
