"""Permutation groups: closure, and the split of a symmetry group G into an abelian part A (the
momenta) and one representative per coset of A (the point group).

The sector engine needs A to be NORMAL in the group G' it is given (G' = A . residues): a residue
p then maps each momentum sector of A onto another (chi_k -> chi_k(p^-1 . p)), which is what makes
stars, little groups and multiplets. A union of whole conjugacy classes of G whose elements commute
pairwise generates a normal abelian subgroup, so :func:`normal_abelian_split` grows A class by class
from every seed class and keeps the largest (ties: more fixed-point-free elements -- the
translations -- then higher element orders).

The engine works through the co-group G'/A per star, so :func:`spatial_split` keeps |G'/A| at most
``_CO_GROUP_CAP``: a group without a large normal abelian subgroup (S_n of an all-to-all or
field-only H) uses a maximal abelian subgroup A and its normaliser G' = N_G(A) instead.

Permutations follow :mod:`qed._perm` (images; compose(a, b)[i] = a[b[i]]).
"""
from __future__ import annotations

from typing import Optional

import numpy as np

from ._perm import CLOSURE_CAP, close_group, compose, inverse, order
from .errors import InvalidRequest

__all__ = ["close_group", "normal_abelian_split", "spatial_split", "split_generator_set",
           "split_nonabelian", "abelian_generators", "maximal_abelian_subgroup", "normaliser_split"]

_CO_GROUP_CAP = 128         # |G'/A|: Oh (48) fits, and so do the accidental groups of small tori


def _rows(perms) -> list[tuple[int, ...]]:
    """A permutation list (any sequence of rows, a numpy array included; None for none) as
    tuples of ints."""
    return [] if perms is None else [tuple(int(x) for x in p) for p in perms]


class _Enumerated:
    """A closed permutation group as sorted rows (the identity is row 0) with a row index, the
    order of each element and whether it moves every site."""

    def __init__(self, G):
        self.elems = sorted({tuple(int(x) for x in g) for g in G})
        self.P = np.asarray(self.elems, dtype=np.int64)
        self.index = {g: i for i, g in enumerate(self.elems)}
        n = self.P.shape[1]
        if self.elems[0] != tuple(range(n)):
            raise InvalidRequest("the permutation group does not contain the identity (not closed)")
        self.orders = np.array([order(p) for p in self.elems], dtype=np.int64)
        self.fpf = (self.P != np.arange(n)).all(axis=1)
        self._right: dict[int, np.ndarray] = {}

    def __len__(self) -> int:
        return len(self.elems)

    def lookup(self, rows: np.ndarray) -> np.ndarray:
        """Indices of the rows of a permutation array; KeyError when one is not in the group."""
        idx = self.index
        return np.fromiter((idx[r] for r in map(tuple, rows.tolist())), dtype=np.int64, count=len(rows))

    def right_mult(self, i: int) -> np.ndarray:
        """t[j] = index of elems[j] . elems[i] (cached)."""
        t = self._right.get(i)
        if t is None:
            t = self._right[i] = self.lookup(self.P[i][self.P])
        return t

    def commutant(self, i: int) -> np.ndarray:
        """Mask of the elements that commute with element i."""
        x = self.P[i]
        return (x[self.P] == self.P[:, x]).all(axis=1)

    def conjugation(self, i: int) -> np.ndarray:
        """t[j] = index of s o x_j o s^-1 (function composition), s = elems[i]."""
        s = self.P[i]
        return self.lookup(s[self.P[:, np.argsort(s)]])

    def commute(self, i: int, j: int) -> bool:
        a, b = self.P[i], self.P[j]
        return bool(np.array_equal(a[b], b[a]))

    def key(self, members: np.ndarray) -> tuple:
        """Preference among subgroups: larger, then more fixed-point-free elements, then higher orders."""
        return (len(members), int(self.fpf[members].sum()),
                tuple(sorted(self.orders[members].tolist(), reverse=True)))


def _closure(E: _Enumerated, gens: list[int]) -> np.ndarray:
    """Membership mask of the subgroup generated by ``gens`` (indices)."""
    right = [E.right_mult(g) for g in gens]
    inside = np.zeros(len(E), dtype=bool)
    inside[0] = True
    frontier = np.zeros(1, dtype=np.int64)
    while frontier.size and right:
        nxt = np.unique(np.concatenate([t[frontier] for t in right]))
        nxt = nxt[~inside[nxt]]
        inside[nxt] = True
        frontier = nxt
    return inside


def _generating_set(E: _Enumerated) -> list[int]:
    """A small generating set of E (indices): high-order elements first, each added only when it
    lies outside the subgroup generated so far (so at most log2 |G| of them)."""
    gens: list[int] = []
    inside = np.zeros(len(E), dtype=bool)
    inside[0] = True
    for c in sorted(range(1, len(E)), key=lambda i: (-int(E.orders[i]), i)):
        if inside[c]:
            continue
        gens.append(c)
        inside = _closure(E, gens)
        if inside.all():
            break
    return gens


def _conjugacy_classes(E: _Enumerated, gens: list[int]) -> tuple[np.ndarray, list[np.ndarray]]:
    """(label per element, members per class): the orbits of conjugation by the generators."""
    conj = [E.conjugation(g) for g in gens]
    label = np.full(len(E), -1, dtype=np.int64)
    classes = []
    for i in range(len(E)):
        if label[i] >= 0:
            continue
        cid = len(classes)
        label[i] = cid
        members, frontier = [i], [i]
        while frontier:
            nxt = []
            for x in frontier:
                for t in conj:
                    y = int(t[x])
                    if label[y] < 0:
                        label[y] = cid
                        members.append(y)
                        nxt.append(y)
            frontier = nxt
        classes.append(np.array(sorted(members), dtype=np.int64))
    return label, classes


def _normal_abelian(E: _Enumerated) -> np.ndarray:
    """Indices of the largest normal abelian subgroup of E the class-union search finds."""
    m = len(E)
    gens = _generating_set(E)
    if all(E.commute(a, b) for a in gens for b in gens):
        return np.arange(m)                                # E is abelian
    label, classes = _conjugacy_classes(E, gens)
    nC = len(classes)
    # K[C, D]: every element of class C commutes with every element of class D. It suffices that one
    # element of C commutes with all of D (conjugating by g maps D onto itself).
    by_class = np.argsort(label, kind="stable")
    starts = np.searchsorted(label[by_class], np.arange(nC))
    K = np.empty((nC, nC), dtype=bool)
    for C, members in enumerate(classes):
        x = E.P[members[0]]
        commutes = (x[E.P] == E.P[:, x]).all(axis=1)
        K[C] = np.logical_and.reduceat(commutes[by_class], starts)
    self_commuting = np.diag(K).copy()
    rep = [int(c[0]) for c in classes]
    priority = sorted(range(nC), key=lambda C: (not E.fpf[rep[C]], -int(E.orders[rep[C]]),
                                               -len(classes[C]), C))
    id_class = int(label[0])
    # One greedy pass per seed class. The union U of the classes it keeps is a group: for a, b in U
    # the class of ab consists of products of elements of U, so it commutes with all of U and with
    # itself, and was kept when the pass reached it. It is normal (a union of classes) and maximal
    # (any class commuting with all of U would have been kept).
    best_key, best = None, np.zeros(1, dtype=np.int64)
    for seed in priority:
        if seed == id_class or not self_commuting[seed]:
            continue
        keep = np.zeros(nC, dtype=bool)
        keep[[id_class, seed]] = True
        compatible = K[:, seed] & self_commuting
        for C in priority:
            if not keep[C] and compatible[C]:
                keep[C] = True
                compatible &= K[:, C]
        members = np.sort(np.concatenate([classes[C] for C in np.flatnonzero(keep)]))
        key = E.key(members)
        if best_key is None or key > best_key:
            best_key, best = key, members
    return best


def _maximal_abelian(E: _Enumerated, seed: Optional[int] = None) -> np.ndarray:
    """Indices of a maximal abelian subgroup containing ``seed``: elements taken greedily,
    fixed-point-free and high order first, each one when it commutes with every one kept so far."""
    order = sorted(range(1, len(E)), key=lambda i: (not E.fpf[i], -int(E.orders[i]), i))
    gens: list[int] = []
    inside = np.zeros(len(E), dtype=bool)
    inside[0] = True
    commuting = np.ones(len(E), dtype=bool)          # commutes with every generator so far
    for c in ([seed] if seed is not None else []) + order:
        if inside[c] or not commuting[c]:
            continue
        gens.append(c)
        commuting &= E.commutant(c)
        inside = _closure(E, gens)
    return np.flatnonzero(inside)


def _normalizer(E: _Enumerated, A: np.ndarray) -> np.ndarray:
    """Indices of N_G(A): the elements g with g A g^-1 = A (checked on generators of A)."""
    in_a = np.zeros(len(E), dtype=bool)
    in_a[A] = True
    sub = _Enumerated(E.P[A])
    keep = np.ones(len(E), dtype=bool)
    inverses = np.argsort(E.P, axis=1)
    for g in _generating_set(sub):
        a = sub.P[g]
        rows = np.take_along_axis(E.P, a[inverses], axis=1)       # g o a o g^-1, one row per g
        keep &= in_a[E.lookup(rows)]
    return np.flatnonzero(keep)


def _cosets(E: _Enumerated, A: np.ndarray, within: np.ndarray) -> list[int]:
    """One representative (the first in sorted order) per coset of A in the subgroup ``within``,
    other than A itself."""
    covered = np.ones(len(E), dtype=bool)
    covered[within] = False
    covered[A] = True
    A_rows = E.P[A]
    reps = []
    for i in within:
        if covered[i]:
            continue
        reps.append(int(i))
        covered[E.lookup(E.P[i][A_rows])] = True              # the coset A . g_i
    return reps


def _checked(E: _Enumerated, A: np.ndarray, within: np.ndarray, residues: list[int]):
    """The split as permutation lists, after asserting that A is normal in ``within`` and that the
    cosets tile it -- guaranteed by construction, so a failure is a bug here."""
    in_a = np.zeros(len(E), dtype=bool)
    in_a[A] = True
    A_rows = E.P[A]
    for r in residues:
        s = E.P[r]
        assert in_a[E.lookup(s[A_rows[:, np.argsort(s)]])].all(), "group split: A is not normal"
    assert len(within) % len(A) == 0 and len(residues) == len(within) // len(A) - 1, \
        "group split: the cosets do not tile the group"
    return [list(E.elems[i]) for i in A], [list(E.elems[i]) for i in residues]


def normal_abelian_split(G) -> tuple[list[list[int]], list[list[int]]]:
    """``(A, residues)`` for a closed permutation group ``G``: ``A`` (sorted, the identity first) the
    largest normal abelian subgroup the class-union search finds, ``residues`` one representative per
    coset of A other than A itself. A may be the identity alone (S_5 on five sites has no non-trivial
    normal abelian subgroup); then every other element is a residue."""
    E = _Enumerated(G)
    A = _normal_abelian(E)
    every = np.arange(len(E))
    return _checked(E, A, every, _cosets(E, A, every))


def spatial_split(G, cap: int = _CO_GROUP_CAP):
    """``(A, residues, diagnostics)``: the split the sector engine uses for the closed group ``G``.

    The normal abelian split of G when its co-group |G/A| is at most ``cap``. Otherwise G is cut
    down to the largest subgroup found among the normalisers N_G(A') (co-group at most ``cap``) of
    maximal abelian subgroups A' grown from one element of every conjugacy class (conjugate seeds
    give conjugate subgroups), or an abelian part alone: smaller than G, but every residue still
    normalises its abelian part. ``diagnostics`` holds one (code, message) pair when G was cut down."""
    E = _Enumerated(G)
    every = np.arange(len(E))
    A = _normal_abelian(E)
    if len(E) // len(A) <= cap:
        return (*_checked(E, A, every, _cosets(E, A, every)), [])
    # (subgroup used, abelian part's key): more reduction first, then a larger abelian part.
    options = [((len(A), E.key(A)), A, A)]
    _, classes = _conjugacy_classes(E, _generating_set(E))
    for members in classes:
        if members[0] == 0:
            continue
        A_c = _maximal_abelian(E, int(members[0]))
        N = _normalizer(E, A_c)
        within = N if len(N) // len(A_c) <= cap else A_c
        options.append(((len(within), E.key(A_c)), A_c, within))
    _, A_use, within = max(options, key=lambda o: o[0])
    msg = (f"the spatial group has {len(E)} elements, but its largest normal abelian subgroup only "
           f"{len(A)}: a co-group of {len(E) // len(A)} exceeds {cap}. Using a subgroup of "
           f"{len(within)} elements (abelian part {len(A_use)}).")
    return (*_checked(E, A_use, within, _cosets(E, A_use, within)), [("co_group_capped", msg)])


def abelian_generators(A) -> list[list[int]]:
    """A generating set of the closed abelian group ``A``: high-order elements first, each one only
    when it lies outside the group generated so far. InvalidRequest when A is not abelian."""
    E = _Enumerated(A)
    gens = _generating_set(E)
    if not all(E.commute(a, b) for a in gens for b in gens):
        raise InvalidRequest("abelian_generators: the group is not abelian")
    return [list(E.elems[i]) for i in gens]


def maximal_abelian_subgroup(G) -> list[list[int]]:
    """A maximal abelian subgroup of the closed group ``G`` (sorted, the identity first), grown
    greedily from its fixed-point-free, high-order elements; G itself when it is abelian."""
    E = _Enumerated(G)
    return [list(E.elems[i]) for i in _maximal_abelian(E)]


def normaliser_split(G, A) -> tuple[list[list[int]], list[list[int]]]:
    """``(A, residues)`` for the closed group ``G`` and an abelian subgroup ``A`` of it: one residue
    per coset of A in its normaliser N_G(A), the largest part of G that stands with A as its
    abelian part."""
    E = _Enumerated(G)
    A_idx = np.sort(E.lookup(np.asarray([[int(x) for x in a] for a in A], dtype=np.int64)))
    N = _normalizer(E, A_idx)
    return _checked(E, A_idx, N, _cosets(E, A_idx, N))


def split_generator_set(generators, star_perms, n_sites=None) -> tuple[list[list[int]], list[list[int]]]:
    """``(A, residues)`` for an explicit split: A the group the generators close (the identity alone
    without generators), residues one per coset of A among ``star_perms``. Raises InvalidRequest when
    A is not abelian or a residue does not normalise it."""
    star = [tuple(int(x) for x in p) for p in star_perms]
    gens = [tuple(int(x) for x in g) for g in generators]
    n = len(gens[0]) if gens else (len(star[0]) if star else n_sites)
    if n is None:
        raise InvalidRequest("split_generator_set: no permutations and no n_sites")
    if not gens:
        A = [tuple(range(n))]
    else:
        A = close_group(gens)
        if A is None:
            raise InvalidRequest(f"the abelian group exceeds the {CLOSURE_CAP}-element closure cap")
    for a in gens:
        for b in gens:
            if compose(a, b) != compose(b, a):
                raise InvalidRequest("the generators of the abelian part do not commute")
    a_set = set(A)
    residues, covered = [], set(a_set)
    for p in star:
        if p in covered:
            continue
        p_inv = inverse(p)
        if any(compose(p, compose(a, p_inv)) not in a_set for a in gens):
            raise InvalidRequest(f"the residue {list(p)} does not normalise the abelian part: the abelian "
                                 "part must be a normal subgroup (pass the permutations as one list and "
                                 "qed.Symmetry chooses one)")
        residues.append(list(p))
        covered.update(compose(p, a) for a in A)
    return [list(a) for a in A], residues


def split_nonabelian(symmetry_or_gens):
    """``(abelian_elements, residue_perms)`` for the sector engine, or a ``str`` saying why there is
    nothing to split.

    * a :class:`qed.Symmetries` (``abelian`` + ``residues``): an explicit split, see
      :func:`split_generator_set`.
    * a permutation list: the group it generates, split by :func:`spatial_split`.
    """
    gens = getattr(symmetry_or_gens, "abelian", None)
    if gens is not None:
        star = _rows(getattr(symmetry_or_gens, "residues", None))
        if len(gens) == 0 and not star:
            return "the symmetry has no spatial generators"
        A, residues = split_generator_set(gens, star)
        if not residues:
            return "no point-group residue outside the abelian group"
        return A, residues
    perms = _rows(symmetry_or_gens)
    if not perms:
        return "no generators given"
    G = close_group(perms)
    if G is None:
        return f"the closed group exceeds the {CLOSURE_CAP}-element cap"
    A, residues, _ = spatial_split(G)
    if not residues:
        return "the input group is abelian -- nothing to project beyond the momentum sectors"
    return A, residues
