"""Dimension-reduction matrix: the projection must ACTUALLY shrink blocks.

Companion to test_lane_exploitation_matrix.py. That file pins WHICH
exploitation engages per lane; this file pins that the engine really works
in blocks of the theoretically reduced dimension -- correctness alone can
hide a lane that quietly solves the big block and relabels it.

The oracle is INDEPENDENT: Burnside orbit counting implemented here from
scratch (fixed-point counts of the group action on bitstrings, character-
weighted), never the engine's own tables. Per symmetry content:

  U(1) Sz            dim = C(N, n_up)
  + abelian k        dim_k = (1/|A|) sum_a chi_k(a)* fix(a)
  + flip at N/2      dim_(k,+/-) = (1/2)[dim_k +/- (1/|A|) sum_a chi_k(a)* fix(aF)]
  + little group     m_sigma per (k, sigma), sum_sigma m_sigma d_sigma = dim_k
  TR / star folds    dims UNCHANGED (folds reduce #solves, never block size)

Engine-side "actual dims" observables (never trusted, always compared):
  * lane B: SectorTag.sector_dim -- the dim of the operator Lanczos ran on
    (tag dims are structural; lane B's unguarded excited VALUES, GAP 10,
    do not matter here)
  * lane A: star plan dim_k0, and the per-block label arrays of
    little_group_full_spectrum -- rows per (k_raw, flip, irrep) = m_sigma,
    the dim of the isotypic block actually diagonalised
  * thermal: per_sector sector_dim across every (n_up, k[, +/-]) block

Matvec regimes: the reduced-CSR sub-mode is the default; the CSR-free
gather walk is forced two ways --
  * in-process via ED_SYM_SECTOR_CSR_BUDGET_GIB (read PER CALL: a tiny
    budget makes every sector decline the CSR and fall back), and
  * end-to-end via ED_SYM_REDUCED_CSR=0 in a SUBPROCESS (that knob is
    resolved once per process, so an in-process monkeypatch after first
    use would silently test nothing).
Both must produce identical dims AND identical physics.
"""
from __future__ import annotations

import itertools
import json
import math
import os
import subprocess
import sys
from collections import Counter

import numpy as np
import pytest

qed = pytest.importorskip("qed")
pytest.importorskip("pynauty")
from qed import _core  # noqa: E402
from qed.point_group_routing import resolve_projection_lane  # noqa: E402

N = 8


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

def _ring_bonds(n=N):
    return [(i, (i + 1) % n) for i in range(n)]


def _torus_bonds():
    """2x4 torus: horizontal wrap on 4 columns, one vertical bond per
    column (2 rows). Gives a 2-generator abelian translation group."""
    bonds = []
    for r in range(2):
        for c in range(4):
            bonds.append((r * 4 + c, r * 4 + (c + 1) % 4))
    for c in range(4):
        bonds.append((c, 4 + c))
    return bonds


def _op(bonds, n=N):
    b = qed.input.HamiltonianBuilder(n)
    b.heisenberg(bonds, J=1.0)
    return b.to_operator()


def _dense(bonds, n=N):
    dim = 1 << n
    H = np.zeros((dim, dim))
    sz = lambda s, i: 0.5 if (s >> i) & 1 else -0.5  # noqa: E731
    for s in range(dim):
        for i, j in bonds:
            H[s, s] += sz(s, i) * sz(s, j)
            if ((s >> i) & 1) != ((s >> j) & 1):
                H[s ^ (1 << i) ^ (1 << j), s] += 0.5
    return H


# ---------------------------------------------------------------------------
# The independent Burnside oracle
# ---------------------------------------------------------------------------

def _perm_apply(s: int, p: list[int]) -> int:
    t = 0
    for i, pi in enumerate(p):
        if (s >> pi) & 1:
            t |= 1 << i
    return t


def _compose(p, q):  # (p*q)(i) = p[q[i]]
    return [p[qi] for qi in q]


def _close(gens, n):
    ident = list(range(n))
    elems = {tuple(ident)}
    frontier = [ident]
    while frontier:
        nxt = []
        for e in frontier:
            for g in gens:
                c = tuple(_compose(g, e))
                if c not in elems:
                    elems.add(c)
                    nxt.append(list(c))
        frontier = nxt
    return [list(e) for e in sorted(elems)]


def _burnside_dims(n, n_up, generators, orders, flip: bool):
    """Multiset of irrep-block dims of the fixed-Sz subspace under the
    abelian group generated by `generators` (optionally x Z2 flip).
    Requires independent generators (|closure| == prod(orders)); the
    caller skips otherwise -- dependent generators would need Smith
    normal form to enumerate characters, and the audit showed the C++
    minimal generators are NOT always independent."""
    A = _close(generators, n)
    if len(A) != int(np.prod(orders)):
        pytest.skip("generators are not independent; character "
                    "enumeration by exponent tuple would be wrong")
    states = [s for s in range(1 << n) if bin(s).count("1") == n_up]
    # element list with exponent tuples, in the same order
    elems = []
    for exps in itertools.product(*[range(o) for o in orders]):
        e = list(range(n))
        for g, k in zip(generators, exps):
            for _ in range(k):
                e = _compose(g, e)
        elems.append((exps, e))
    mask = (1 << n) - 1
    fix_plain = {tuple(x): sum(1 for s in states if _perm_apply(s, e) == s)
                 for x, e in elems}
    if flip:
        fix_flip = {tuple(x): sum(1 for s in states
                                  if _perm_apply(s ^ mask, e) == s)
                    for x, e in elems}
    dims = []
    for qs in itertools.product(*[range(o) for o in orders]):
        acc_p = acc_f = 0.0
        for exps, _e in elems:
            chi = np.prod([np.exp(-2j * np.pi * q * k / o)
                           for q, k, o in zip(qs, exps, orders)])
            acc_p += (np.conj(chi) * fix_plain[tuple(exps)]).real
            if flip:
                acc_f += (np.conj(chi) * fix_flip[tuple(exps)]).real
        if not flip:
            d = acc_p / len(elems)
            dims.append(round(d))
        else:
            for s in (+1, -1):
                d = (acc_p + s * acc_f) / (2 * len(elems))
                dims.append(round(d))
    dims = [d for d in dims if d > 0]
    assert sum(dims) == math.comb(n, n_up), "oracle covering failed"
    return Counter(dims)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module", params=["ring", "torus24"])
def model(request):
    bonds = _ring_bonds() if request.param == "ring" else _torus_bonds()
    H = _op(bonds)
    gens = qed.find_symmetries(H, verbose=False).full_set
    return request.param, bonds, H, gens


# ===========================================================================
# 1. Lane B: every (n_up, k[, +/-]) operator dim == Burnside
# ===========================================================================

@pytest.mark.parametrize("flip", ["auto", 0])
def test_lane_b_sector_dims_match_burnside(model, flip):
    """SectorTag.sector_dim is the dim of the operator the per-sector
    solve ran on. Its multiset must equal independent orbit counting --
    with the flip axis engaged the (k) sectors must REALLY split into
    the smaller (k, +/-) halves, not merely relabel."""
    name, bonds, H, gens = model
    n_up = N // 2
    r = qed.solve(H, num_eigenvalues=math.comb(N, n_up), symmetry=gens,
                  sz=n_up, point_group="off", spin_flip=flip,
                  device="cpu", verbose=False)
    actual = Counter(t.sector_dim for t in r.sector_tags)
    flip_engaged = (flip == "auto")
    expect = _burnside_dims(N, n_up, [list(g) for g in gens.generators],
                            list(gens.orders), flip=flip_engaged)
    assert actual == expect, (
        f"[{name}] lane B dims {sorted(actual.elements())} != Burnside "
        f"{sorted(expect.elements())} (flip={flip})")
    # total covering: the blocks tile the subspace
    assert sum(actual.elements()) == math.comb(N, n_up)


def test_lane_b_dims_invariant_under_tr_fold(model):
    """Time reversal is a FOLD: it may halve the number of solves but
    must never change any block's dimension."""
    name, bonds, H, gens = model
    n_up = N // 2
    kw = dict(num_eigenvalues=math.comb(N, n_up), symmetry=gens, sz=n_up,
              point_group="off", device="cpu", verbose=False)
    d_on = Counter(t.sector_dim
                   for t in qed.solve(H, time_reversal="auto", **kw)
                   .sector_tags)
    d_off = Counter(t.sector_dim
                    for t in qed.solve(H, time_reversal=0, **kw)
                    .sector_tags)
    assert d_on == d_off


# ===========================================================================
# 2. Lane A: momentum sectors and isotypic blocks
# ===========================================================================

def _lg_out(H, gens, n_up, **kv):
    lane = resolve_projection_lane(gens, point_group="auto",
                                   consumer="full_spectrum",
                                   eigenvalues_only=True, verbose=False)
    assert lane.mode == "project", lane.reason
    return dict(_core.little_group_full_spectrum(
        H, lane.A, lane.residues, n_up=n_up, sz_parity=-1,
        spin_flip=kv.get("spin_flip", -1),
        time_reversal=kv.get("time_reversal", -1),
        plan_only=kv.get("plan_only", False)))


def test_lane_a_momentum_sector_dims_match_burnside(model):
    """Star plan dim_k0, expanded by star membership (members are
    isospectral, hence equal-dim), must reproduce the Burnside multiset
    of extended (k, +/-) sector dims."""
    name, bonds, H, gens = model
    n_up = N // 2
    stars = [dict(s) for s in
             _lg_out(H, gens, n_up, plan_only=True)["stars"]]
    actual = Counter()
    for s in stars:
        actual.update([s["dim_k0"]] * s["star_size"])
    flip_engaged = any(s["flip_parity"] in (0, 1) for s in stars)
    expect = _burnside_dims(N, n_up, [list(g) for g in gens.generators],
                            list(gens.orders), flip=flip_engaged)
    assert actual == expect, (
        f"[{name}] lane A momentum dims {sorted(actual.elements())} != "
        f"Burnside {sorted(expect.elements())}")


def test_lane_a_isotypic_blocks_really_reduce(model):
    """The strong claim: inside a momentum sector with a nontrivial
    little co-group the engine must diagonalise the ISOTYPIC blocks
    W_sigma^dag H W_sigma -- of dim m_sigma STRICTLY below dim_k0 --
    and their sizes must tile the sector: sum_sigma m_sigma d_sigma =
    dim_k0. m_sigma is measured from the OUTPUT (rows per (k0, sigma)
    label), not from any engine-internal check."""
    name, bonds, H, gens = model
    n_up = N // 2
    out = _lg_out(H, gens, n_up)
    stars = [dict(s) for s in out["stars"]]
    rows = list(zip(out["block_k_raw"], out["block_flip_parity"],
                    out["block_irrep"], out["block_irrep_dim"],
                    out["multiplicities"]))
    projected_any = False
    for s in stars:
        if not s.get("projected"):
            continue
        projected_any = True
        k0, order = s["k0"], s["little_order"]
        d_sigma = list(s["little_irrep_dims"])
        # m_sigma = number of output rows labelled (this star, sigma)
        srows = [r for r in rows if r[0] == (k0 % len(out
                 ["irrep_characters"])) and (s["flip_parity"] < 0
                 or r[1] == s["flip_parity"])]
        m = Counter(r[2] for r in srows)
        tot = sum(m[i] * d_sigma[i] for i in m)
        assert tot == s["dim_k0"], (
            f"[{name}] star k0={k0}: isotypic tiling "
            f"sum m_sigma*d_sigma = {tot} != dim_k0 = {s['dim_k0']}")
        assert max(m.values()) < s["dim_k0"], (
            f"[{name}] star k0={k0}: no block is smaller than the "
            f"momentum sector -- projection did not reduce")
    assert projected_any, (
        f"[{name}] no star was projected at all -- the little-group "
        f"engine never engaged")
    # global covering from output multiplicities
    assert sum(out["multiplicities"]) == math.comb(N, n_up)
    # correctness anchor: full multiset == dense block
    Hd = _dense(bonds)
    states = [s for s in range(1 << N) if bin(s).count("1") == n_up]
    ref = np.linalg.eigvalsh(Hd[np.ix_(states, states)])
    np.testing.assert_allclose(np.sort(np.asarray(out["eigenvalues"])),
                               ref, atol=1e-9)


# ===========================================================================
# 3. Full-space 'Symm' mode (no Sz named): blocks of the 2^N space
# ===========================================================================

def test_full_space_symm_mode_dims(model):
    """The 'Symm' row of the four-mode taxonomy: full Hilbert space +
    spatial projection. Oracle = Burnside over ALL 2^N states."""
    name, bonds, H, gens = model
    r = qed.solve(H, num_eigenvalues=1 << N, symmetry=gens,
                  auto_sz=False, point_group="off", spin_flip=0,
                  device="cpu", verbose=False)
    actual = Counter(t.sector_dim for t in r.sector_tags)
    A = _close([list(g) for g in gens.generators], N)
    if len(A) != int(np.prod(list(gens.orders))):
        pytest.skip("dependent generators")
    states = list(range(1 << N))
    elems = []
    for exps in itertools.product(*[range(o) for o in gens.orders]):
        e = list(range(N))
        for g, k in zip(gens.generators, exps):
            for _ in range(k):
                e = _compose(list(g), e)
        elems.append((exps, e))
    fix = {tuple(x): sum(1 for s in states if _perm_apply(s, e) == s)
           for x, e in elems}
    dims = []
    for qs in itertools.product(*[range(o) for o in gens.orders]):
        acc = 0.0
        for exps, _e in elems:
            chi = np.prod([np.exp(-2j * np.pi * q * k / o)
                           for q, k, o in zip(qs, exps, gens.orders)])
            acc += (np.conj(chi) * fix[tuple(exps)]).real
        dims.append(round(acc / len(elems)))
    expect = Counter(d for d in dims if d > 0)
    assert sum(expect.elements()) == 1 << N
    assert actual == expect, (
        f"[{name}] Symm-mode dims {sorted(actual.elements())} != "
        f"Burnside {sorted(expect.elements())}")


# ===========================================================================
# 4. Matvec regimes: reduced-CSR vs CSR-free gather walk
# ===========================================================================

def _project_lane_fingerprint(H, gens, n_up):
    """(dims-per-star, m_sigma counts, lowest-6) -- everything the regime
    must NOT change."""
    out = _lg_out(H, gens, n_up)
    stars = [dict(s) for s in out["stars"]]
    dims = sorted((s["k0"], s["dim_k0"]) for s in stars)
    msig = Counter(zip(out["block_k_raw"], out["block_irrep"]))
    eigs = np.sort(np.asarray(out["eigenvalues"]))[:6]
    return dims, msig, eigs


def test_gather_walk_fallback_same_dims_same_physics(model, monkeypatch):
    """ED_SYM_SECTOR_CSR_BUDGET_GIB is read per call: a vanishing budget
    makes EVERY sector decline the reduced CSR and take the CSR-free
    gather walk. Dims and eigenvalues must be identical to the CSR
    regime. (The ED_SYM_REDUCED_CSR knob itself is process-cached --
    see the subprocess cell below for that axis.)"""
    name, bonds, H, gens = model
    n_up = N // 2
    dims_csr, msig_csr, e_csr = _project_lane_fingerprint(H, gens, n_up)
    monkeypatch.setenv("ED_SYM_SECTOR_CSR_BUDGET_GIB", "1e-9")
    dims_st, msig_st, e_st = _project_lane_fingerprint(H, gens, n_up)
    assert dims_csr == dims_st
    assert msig_csr == msig_st
    np.testing.assert_allclose(e_csr, e_st, atol=1e-10)


_SUBPROC_SCRIPT = r"""
import sys, json, math
sys.meta_path = [f for f in sys.meta_path
                 if 'editable' not in type(f).__module__.lower()]
sys.path.insert(0, 'python')
import numpy as np
import qed
from qed import _core
from qed.point_group_routing import resolve_projection_lane
bonds = json.loads(sys.argv[1])
b = qed.input.HamiltonianBuilder(8)
b.heisenberg([tuple(x) for x in bonds], J=1.0)
H = b.to_operator()
gens = qed.find_symmetries(H, verbose=False).full_set
lane = resolve_projection_lane(gens, point_group="auto",
                               consumer="full_spectrum",
                               eigenvalues_only=True, verbose=False)
out = dict(_core.little_group_full_spectrum(
    H, lane.A, lane.residues, n_up=4, sz_parity=-1,
    spin_flip=-1, time_reversal=-1))
stars = [dict(s) for s in out["stars"]]
print("RESULT" + json.dumps({
    "dims": sorted([s["k0"], s["dim_k0"]] for s in stars),
    "eigs": list(np.sort(np.asarray(out["eigenvalues"]))[:6]),
}))
"""


def test_forced_stream_regime_subprocess_same_dims(model):
    """ED_SYM_REDUCED_CSR=0 end-to-end: resolved once per process, so it
    gets its own interpreter. The forced CSR-free regime must report the
    same star dims and the same lowest eigenvalues as this process's
    default (reduced-CSR) regime."""
    name, bonds, H, gens = model
    n_up = N // 2
    dims_csr, _msig, e_csr = _project_lane_fingerprint(H, gens, n_up)
    env = dict(os.environ, ED_SYM_REDUCED_CSR="0")
    proc = subprocess.run(
        [sys.executable, "-c", _SUBPROC_SCRIPT, json.dumps(bonds)],
        capture_output=True, text=True, env=env,
        cwd=os.path.dirname(os.path.dirname(os.path.dirname(
            os.path.abspath(__file__)))))
    assert proc.returncode == 0, proc.stderr[-2000:]
    line = [ln for ln in proc.stdout.splitlines()
            if ln.startswith("RESULT")][-1]
    got = json.loads(line[len("RESULT"):])
    assert [list(x) for x in map(list, dims_csr)] == got["dims"]
    np.testing.assert_allclose(e_csr, np.asarray(got["eigs"]), atol=1e-10)


# ===========================================================================
# 5. Combination sweep: dims match theory under every toggle combo
# ===========================================================================

@pytest.mark.parametrize("flip,tr", [("auto", "auto"), ("auto", 0),
                                     (0, "auto"), (0, 0)])
def test_combo_sweep_dims_and_gs(model, flip, tr):
    """Any permutation/combination of (flip, TR) on lane B: block dims
    must equal Burnside for exactly the mechanisms that project (flip
    changes dims at N/2; TR never does), and the GS must stay exact."""
    name, bonds, H, gens = model
    n_up = N // 2
    r = qed.solve(H, num_eigenvalues=1, symmetry=gens, sz=n_up,
                  point_group="off", spin_flip=flip, time_reversal=tr,
                  device="cpu", verbose=False)
    Hd = _dense(bonds)
    states = [s for s in range(1 << N) if bin(s).count("1") == n_up]
    ref0 = float(np.linalg.eigvalsh(Hd[np.ix_(states, states)])[0])
    assert float(r.eigenvalues[0]) == pytest.approx(ref0, abs=1e-8)
    # a full-window run exposes every sector's dim
    rt = qed.solve(H, num_eigenvalues=math.comb(N, n_up), symmetry=gens,
                   sz=n_up, point_group="off", spin_flip=flip,
                   time_reversal=tr, device="cpu", verbose=False)
    actual = Counter(t.sector_dim for t in rt.sector_tags)
    expect = _burnside_dims(N, n_up, [list(g) for g in gens.generators],
                            list(gens.orders), flip=(flip == "auto"))
    assert actual == expect, (
        f"[{name}] flip={flip} tr={tr}: dims "
        f"{sorted(actual.elements())} != {sorted(expect.elements())}")
